### ISSUE TITLE
I got an Intel MKL FATAL ERROR

### ISSUE THREAD

**Issue by zhangbw3187** [arzwa/wgd#16]
Hi Dr. Zwaenepoel, 
I successfully installed the software, but got an error when I tried to ran "wgd ksd" as:
`wgd ksd -o ./ -n 12 ./blabla.blast.tsv.mcl blabla.cds.fa`
The mcl file is produced by "wgd mcl"

the error said it cannot load `/root/anaconda3/lib/python3.7/site-packages/sklearn/metrics/../../../../libmkl_core.so.`

But I can see there is a file called `libmkl_core.so` in that path,
and the r+x authority of the file (as well as the whole path to the file) has been given to every user.

Could you please help me to see what's wrong with it?
Many thanks,
Bowen

```
2019-03-15 10:38:08: INFO	Performing analysis on gene family GF_006004
2019-03-15 10:38:08: INFO	Performing analysis on gene family GF_006005
2019-03-15 10:38:08: INFO	Performing analysis on gene family GF_006006
2019-03-15 10:38:08: INFO	Performing analysis on gene family GF_006007
2019-03-15 11:44:23: INFO	Analysis done
2019-03-15 11:44:23: INFO	Making results data frame
2019-03-15 11:45:55: INFO	Removing tmp directory
2019-03-15 11:45:57: INFO	Computing weights, outlier cut-off at Ks > 5
Intel MKL FATAL ERROR: Cannot load /root/anaconda3/lib/python3.7/site-packages/sklearn/metrics/../../../../libmkl_core.so.
```

**Comment by arzwa** [comment]
Hi Bowen, 

That's weird, so the analyses all went correctly but then the last step failed? From the looks of it, it's some problem with your python packages. From similar issues (e.g. [here](https://github.com/ContinuumIO/anaconda-issues/issues/720)), I think you might want to try reinstalling numpy using `conda install  -f  numpy`, (or perhaps `conda install  -f  sklearn`, just guessing).  You might want to retry then on a subset of your gene families (e.g. use 10 random lines from your mcl file instead of the full mcl file) to see if it works.

If that doesn't work, than I would advise you to install `wgd` in a different environment (e.g. using virtualenv or (mini)conda) with python3.6  (I see you are using python3.7, which I haven't tested yet).

Let me know if that solves your troubles, 

Arthur (not a 'Dr.' yet BTW ;)

**Comment by zhangbw3187** [comment]
Thank you Arthur,
I tried to reinstalled numpy and sklearn, but it still doesn't work. Same error.

I couldn't reinstall the python of this system, but I will try to borrow another machine with different environment. I will follow up after I got it.

Best,
Bowen

**Comment by zhangbw3187** [comment]
Hi Arthur,
I got Python3.6, it works fine now.

Thank you and best wishes!

Bowen

**Comment by arzwa** [comment]
OK, great! I'll have to get a look at possible issues with Python3.7. Thanks!
