### ISSUE TITLE
Error during ksd with some gene families

### ISSUE THREAD

**Issue by igigkuo** [arzwa/wgd#29]
Hi,

I am calculating ks with "wgd ksd". I really enjoy using wgd, and the whole process went well with most datasets, but in some cases, the program first went well and then stopped with an error report for a particular gene family, and it seems to be related to the failure of creating the Ks file.

The input files and the error report are here:
[test.zip](https://github.com/arzwa/wgd/files/4497053/test.zip)

My command is:
wgd ksd -n 10 Bo.Bo.homo Bo.Bo.cds

I would be grateful if you can help me with this error. Many thanks to your help!

**Comment by arzwa** [comment]
Hi, I think this is due to a bug that is already fixed in the latest wgd version on the master branch. From the error report it seems you are not using that latest version (my bad, I should have tagged a new release, which I did now - see release v1.0.1). Please install the latest version and check if you still have issues.

**Comment by igigkuo** [comment]
The problem is solved with the new version!! That's great!!!  Thanks a lot!
